export default {
  cameraGroups: [],
  selectedCameraGroup: {id: null, name: null, cameras: [], guards: []},
  fetchInProcess: false,
  fetchError: false,
  addCameraGroupCameraInProcess: false,
  addCameraGroupCameraError: '',
  addCameraGroupCameraSuccess: false,
  addCameraGroupInProcess: false,
  addCameraGroupError: '',
  addCameraGroupSuccess: false,
  shareCameraGroupInProcess: false,
  shareCameraGroupError: '',
  shareCameraGroupSuccess: false,
  editCameraGroupInProcess: false,
  editCameraGroupSuccess: false,
  editCameraGroupError: '',
  removeGuardInProcess: false,
  removeGuardError: '',
  removeCameraGroupInProcess: false,
  removeCameraGroupError: '',
  removeCameraGroupSuccess: false,
  addedCameraData: '',
  bvcCameraConnection: false,
  bvcCameraConnectionFail: false,
  bvcCameraConnectionFailId: ''
}
