export default {
  cameraGroups: [],
  cameraGroupsAdmin: [],
  selectedCameraGroup: {id: null, name: null, cameras: [], userCameraGroupPrivileges: []},
  fetchInProcess: false,
  fetchError: false,
  addCameraGroupInProcess: false,
  addCameraGroupError: '',
  addCameraGroupSuccess: false,
  shareCameraGroupInProcess: false,
  shareCameraGroupError: '',
  shareCameraGroupSuccess: false,
  editCameraGroupInProcess: false,
  editCameraGroupSuccess: false,
  editCameraGroupError: '',
  removeUserCameraGroupPrivilegeInProcess: false,
  removeUserCameraGroupPrivilegeError: '',
  removeCameraGroupInProcess: false,
  removeCameraGroupError: '',
  removeCameraGroupSuccess: false,
  addedCameraData: '',
  cameraConnection: false,
  cameraConnectionFail: false,
  cameraConnectionFailId: '',
  enableCameraGroupInProcess: false,
  disableCameraGroupInProcess: false
}
