export default {
  cameraGroups: [],
  selectedCameraGroup: {id: null, name: null, cameras: [], userCameraGroupPrivileges: []},
  fetchInProcess: false,
  fetchError: false,
  addCameraGroupInProcess: false,
  addCameraGroupError: '',
  addCameraGroupSuccess: false,
  shareCameraGroupInProcess: false,
  shareCameraGroupError: '',
  shareCameraGroupSuccess: false,
  editCameraGroupInProcess: false,
  editCameraGroupSuccess: false,
  editCameraGroupError: '',
  removeGuardInProcess: false,
  removeGuardError: '',
  removeCameraGroupInProcess: false,
  removeCameraGroupError: '',
  removeCameraGroupSuccess: false,
  addedCameraData: '',
  cameraConnection: false,
  cameraConnectionFail: false,
  cameraConnectionFailId: ''
}
