export default {
  authRtspUrl: null,
  fetchInProcess: false,
  fetchError: '',
  deleteCameraInProcess: false,
  deleteCameraSucess: false,
  deleteCameraError: '',
  imageUpdateInProgress: false,
  imageUpdateInProgressId: '',
  refreshCameraError: '',
  refreshCameraErrorId: '',
  imageUpdateSuccess: false,
  imageUpdateSuccessId: '',
  image: false,
  disabledFlag: false,
  editCameraInProcess: false,
  editCameraSuccess: false,
  editCameraError: '',
  cameraConnectionEnabled: false,
  cameraConnectionId: '',
  time_zone: null
}
